name: Quality

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]

jobs:
  install_poetry:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          cache: poetry
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry Package
        run: poetry install
      - name: mypy
        run: poetry run mypy src --junit-xml=junit/mypy-${{ matrix.python-version }}.xml
      - name: Pydocstyle
        run: poetry run pydocstyle src
      - name: Pylint
        run: poetry run pylint --version && poetry run pylint src
      - name: Flake8
        run: poetry run flake8 --format junit-xml src > junit/flake8-${{ matrix.python-version }}.xml
      - name: Upload pytest test results
        uses: actions/upload-artifact@v3
        with:
          name: Lint-results-${{ matrix.python-version }}
          path: junit/*.xml
        if: ${{ always() }} # Also run when steps before failed
