name: Version tag

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Version tag if last commit was Bump
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: Is last commit bump version
        id: version_number
        continue-on-error: true
        run: |
          OUTPUT=$(git show -q | grep "[BUMP] Package" | awk '{print $5}')
          echo "OUTPUT=$OUTPUT" >> $GITHUB_OUTPUT
      - name: Git tag & push
        if: steps.version_number.outputs.OUTPUT != ''
        run: |
          git tag ${{ steps.version_number.outputs.OUTPUT }}
          git push --tags
