name: Version bump

on:
  workflow_dispatch:
    inputs:
      versionPart:
        description: "Version bump part"
        required: true
        default: patch
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  deploy:
    name: Version bump on release branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
      - name: Install Poetry
        run: pipx install poetry
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
          cache: "poetry"
      - name: Setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git checkout -b release
      - name: Bump Version
        run: |
          VERSION=$(poetry version --short)
          poetry version ${{ github.event.inputs.versionPart }}
          BUMPED_VERSION=$(poetry version --short)
      - name: Commiting Version change
        run: |
          git add --all
          git commit -m "[BUMP] Package $VERSION to $BUMPED_VERSION"
      - name: Git push
        run: |
          git push origin release
      - name: Create Pull Request
        uses: actions/github-script@v6
        with:
          script: |
            const { repo, owner } = context.repo;
            const result = await github.rest.pulls.create({
              title: 'Release version',
              owner,
              repo,
              head: 'release',
              base: 'main',
              body: [
                'This PR is auto-generated by',
                '[actions/github-script](https://github.com/actions/github-script).'
              ].join('\n')
            });
